# Generated by Django 5.1.1 on 2025-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('purchased_price', models.FloatField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
